In [1]:
# https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/introduction-to-tensorflow

In [ ]:
# datatype
# shape
# 

In [2]:
import tensorflow as tf

2022-05-25 08:07:45.150523: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-25 08:07:45.150560: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [3]:
string = tf.Variable("This is a string", tf.string)

2022-05-25 08:08:26.173825: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-25 08:08:26.173860: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-25 08:08:26.173883: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (b573b01cafdd): /proc/driver/nvidia/version does not exist
2022-05-25 08:08:26.210977: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>

In [5]:
type(string)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [6]:
number = tf.Variable(324, tf.int16)

In [7]:
number

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>

In [8]:
num2 = tf.Variable([[1,2], [3,4]], tf.int16)

In [9]:
num2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
float01 = tf.Variable([[1.2], [2.3], [4.5]])

In [11]:
float01

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.2],
       [2.3],
       [4.5]], dtype=float32)>

In [12]:
float02 = tf.Variable([[1.2], [2.3], [4.5]], tf.float64)

In [13]:
float02

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.2],
       [2.3],
       [4.5]], dtype=float32)>

In [ ]:
# shape
# rank/degree of tensors 
# the number of dimensions inside the tensor
# the number of elements inside the shape
# shape=(3,1)

In [15]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank1_tensor 

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>

In [16]:
rank2_tensor = tf.Variable([["Test", "ok"], ["Test", "yes"]], tf.string)
rank2_tensor 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Test', b'ok'],
       [b'Test', b'yes']], dtype=object)>

In [17]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
type(tf.rank(rank2_tensor))

tensorflow.python.framework.ops.EagerTensor

In [19]:
int(tf.rank(rank2_tensor))

2

In [20]:
rank2_tensor.shape

TensorShape([2, 2])

In [22]:
type(rank2_tensor.shape)

tensorflow.python.framework.tensor_shape.TensorShape

In [23]:
tensor1 = tf.ones([1,2,3])
tensor1 

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [24]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor2 

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [25]:
tensor3 = tf.reshape(tensor2, [3, -1])
tensor3 
# -1 infers that the number needs to be
# the reshape shouldn't lose any elements

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [26]:
my_tensor_01 = tf.zeros([5,5,5,5])
print(my_tensor_01)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.

In [27]:
5**4

625

In [30]:
# flat out the tensor above
# to be a rank 1 tensor, that is a vector
my_tensor_02 = tf.reshape(my_tensor_01, [-1])
# there should be 5**4 = 625 elements

In [31]:
# this is a horizontal vector
my_tensor_02


<tf.Tensor: shape=(625,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [32]:
tf.Variable()

ValueError: The `initial_value` arg to `tf.Variable` must be specified except when you are not providing a `variable_def`. You provided neither.

In [33]:
tf.Flowing()

AttributeError: module 'tensorflow' has no attribute 'Flowing'

In [37]:
tf.Placeholder

AttributeError: module 'tensorflow' has no attribute 'Placeholder'

In [35]:
tf.SparseTensor()

TypeError: __init__() missing 3 required positional arguments: 'indices', 'values', and 'dense_shape'

In [36]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const')>

In [1]:
# https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/core-learning-algorithms 