In [2]:
a = 1 + 1

2

In [1]:
sumsq(x, y) = x^2 + y^2;

In [3]:
my_func(x) = 10*s

my_func (generic function with 1 method)

In [5]:
my_func(x) = 10*x

my_func (generic function with 1 method)

In [6]:
my_func(10)

100

In [13]:
N = 100_000; x = 0;
for i = 1:N
    if sumsq(rand(), rand()) < 1.0
        x += 1;
    end
end
println(x)

78367


In [14]:
x = 2; typeof(x)

Int64

In [15]:
x = 2.0; typeof(x)

Float64

In [16]:
WORD_SIZE

LoadError: UndefVarError: WORD_SIZE not defined

In [18]:
Int8

Int8

In [19]:
Int16 

Int16

In [20]:
Int32

Int32

In [21]:
Int64

Int64

In [22]:
Int128

Int128

In [27]:
x^300
# this is overflow

0

In [31]:
# effectively it is 2^(32*6) = 2^(192)
x = BigInt(2^32)
x^6

6277101735386680763835789423207666416102355444464034512896

In [32]:
typeof(x)

BigInt

In [36]:
UInt

UInt64

In [35]:
UInt8

UInt8

In [37]:
UInt32

UInt32

In [38]:
UInt128

UInt128

In [39]:
typeof(UInt128)

DataType

In [50]:
for T = [Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128]
    println("$(lpad(T, 10)): [$(typemin(T)), $(typemax(T))]")
end

      Int8: [-128, 127]
     Int16: [-32768, 32767]
     Int32: [-2147483648, 2147483647]
     Int64: [-9223372036854775808, 9223372036854775807]
    Int128: [-170141183460469231731687303715884105728, 170141183460469231731687303715884105727]
     UInt8: [0, 255]
    UInt16: [0, 65535]
    UInt32: [0, 4294967295]
    UInt64: [0, 18446744073709551615]
   UInt128: [0, 340282366920938463463374607431768211455]


In [41]:
println("$(Int8)")

Int8


In [43]:
println("$(lpad(Int8,10))")

      Int8


In [52]:
# everytime that we have overflow julia will give 0?
2^129


0

In [55]:
typeof(1)

Int64

In [53]:
typeof(1999999999999999999)

Int64

In [56]:
typeof(19999999999999999999999)

Int128

In [54]:
# automatically julia will assign the type of BigInt if the 
# number passes the size of an Int64
typeof(19999999999999999999999999999999999999999999999999999)

BigInt

In [57]:
x = 7; y = 5; x/y

1.4

In [58]:
typeof(x/y)

Float64

In [59]:
div(x,y)

1

In [60]:
rem(x,y)

2

In [61]:
x % y

2

In [62]:
# note that \ is an operator in julia
x\y
# it is the same as y/x

0.7142857142857143

In [63]:
y/x

0.7142857142857143

In [ ]:
# binary
# octal
# hexadecimal

In [64]:
x = 0b1101101

0x6d

In [65]:
x = 0x10b5

0x10b5

In [66]:
typeof(x)

UInt16

In [67]:
x = 0xbb31; y = 0xaa5f;

In [70]:
x ⊻ y

0x116e

In [71]:
x ⊼ y

0x55ee

In [72]:
α = 10

10

In [73]:
β
γ
Κ
κ

LoadError: UndefVarError: β not defined

In [74]:
0b10 ⊻ 0b01

0x03

In [75]:
typeof(0b10)

UInt8

In [76]:
typeof(0b111)

UInt8

In [77]:
0b111

0x07

In [78]:
0x10

0x10

In [79]:
typeof(0x10)

UInt8

In [80]:
typeof(0x1111)

UInt16

In [81]:
typeof(0x111111)

UInt32

In [82]:
typeof(0x11111111)

UInt32

In [83]:
typeof(0x1111111111)

UInt64

In [84]:
typeof(0x111111111111)

UInt64

In [86]:
typeof(0x11111111111111111111)

UInt128

In [87]:
0xbb31

0xbb31

In [88]:
0xbb31 << 8

0x3100

In [89]:
0xbb31 >> 8

0x00bb

In [91]:
x = 0xbb31

0xbb31

In [92]:
typeof(x)

UInt16

In [94]:
y = Int16(x)

LoadError: InexactError: check_top_bit(Int16, 47921)

In [96]:
typeof(true)

Bool

In [97]:
DataType

DataType

In [98]:
typeof(DataType)

DataType

In [101]:
x = 0xbb31
y = true
# true is transformed into 1 when adding
x+y

0xbb32

In [102]:
x = 0xbb31
y = false
x+y

0xbb31

In [103]:
A = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]

15-element Vector{Int64}:
   0
   1
   1
   2
   3
   5
   8
  13
  21
  34
  55
  89
 144
 233
 377

In [104]:
A = [1:10]

1-element Vector{UnitRange{Int64}}:
 1:10

In [105]:
B = [1:3:15]

1-element Vector{StepRange{Int64, Int64}}:
 1:3:13

In [106]:
C = [1:0.5:5]

1-element Vector{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}:
 1.0:0.5:5.0

In [111]:
[Int64(x) for x in zeros(15)] 

15-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [114]:
[Int64(x) for x in ones(15)]

15-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [115]:
rand(1:100, 15)

15-element Vector{Int64}:
  3
 12
 45
 38
 51
  8
 82
 49
 92
 31
 21
 65
 46
  2
 94

In [117]:
A = Vector(20)

LoadError: MethodError: no method matching (Vector)(::Int64)
Closest candidates are:
  (Vector)() at baseext.jl:38
  (Vector)(::SparseArrays.AbstractSparseVector{Tv}) where Tv at /opt/julia-1.8.2/share/julia/stdlib/v1.8/SparseArrays/src/sparsevector.jl:947
  (Vector)(::SuiteSparse.CHOLMOD.Dense{T}) where T at /opt/julia-1.8.2/share/julia/stdlib/v1.8/SuiteSparse/src/cholmod.jl:856
  ...

In [122]:
Vector{Float64}()

LoadError: MethodError: no method matching Vector{Float64}(::Int64)
Closest candidates are:
  Vector{T}() where T at boot.jl:478
  Vector{T}(::AbstractRange{T}) where T at range.jl:1361
  Array{T, N}(::Core.Compiler.BitArray{N}) where {T, N} at bitarray.jl:495
  ...

In [126]:
A = zeros(15)

15-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [127]:
A = zeros(15)
A[1] = 0
A[2] = 1
[A[i] = A[i-1] + A[i-2] for i = 3:length(A)]

13-element Vector{Float64}:
   1.0
   2.0
   3.0
   5.0
   8.0
  13.0
  21.0
  34.0
  55.0
  89.0
 144.0
 233.0
 377.0

In [130]:
# this create an empty array
A = Int64[];
# push values into the array
push!(A, 1)
push!(A, 2)
push!(A, 3)


3-element Vector{Int64}:
 1
 2
 3

In [131]:
pop!(A)

3

In [132]:
A = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [133]:
A = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [ ]:
# note that using commas we create a vector 
# which is a column array
# using spaces we create a matrix with 1 line a 3 columns

In [134]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [136]:
using Printf

In [137]:
for i in (1:length(A)) @printf("%ld: %ld\n", i, A[i]); end
# this will go through the elements of the matrix 
# from top down and then left to right


1: 1
2: 4
3: 2
4: 5
5: 3
6: 6


In [138]:
# counts all elements in the matrix
length(A)

6

In [139]:
A[1,2]

2

In [140]:
A[2]

4

In [142]:
A[6]

6

In [143]:
# reshape matrix
B = reshape(A, 3, 2)

3×2 Matrix{Int64}:
 1  5
 4  3
 2  6