In [1]:
import tensorflow as tf

2022-05-19 00:41:35.613983: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-19 00:41:35.614022: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [3]:
my_tensor = tf.Variable("Test", tf.string)

In [4]:
type(my_tensor)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [5]:
tf.rank(my_tensor) # tensor of rank 0

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
my_tensor_2 = tf.Variable(["Test", "Again"], tf.string)

In [7]:
tf.rank(my_tensor_2) # should be rank 1
# <tf.Tensor: shape=(), dtype=int32, numpy=1>

<tf.Tensor: shape=(), dtype=int32, numpy=1>