In [ ]:
# ---------------------------------------- #
# study notes:
# chapter 3 of aurelian geron's book
# Multilabel Classification
# ---------------------------------------- #

In [15]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import f1_score

In [3]:
mnist = fetch_openml("mnist_784", version=1) # <=== takes a long time to run...
X, y = mnist["data"].values, mnist["target"].values
y = y.astype(np.uint8)

# let's use a smaller dataset to run this example for quick results
X_train, X_test, y_train, y_test = X[:6_000], X[6_000:7_000], y[:6_000], y[6_000:7_000]
# X_train, X_test, y_train, y_test = X[:60_000], X[60_000:], y[:60_000], y[60_000:]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))

In [4]:
y_train_large = (y_train >= 7)
y_train_odd = (y_train % 2)
y_multilabel = np.c_[y_train_large, y_train_odd]

In [5]:
y_multilabel

array([[0, 1],
       [0, 0],
       [0, 0],
       ...,
       [1, 0],
       [0, 0],
       [1, 1]], dtype=uint8)

In [7]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, y_multilabel)


KNeighborsClassifier()

In [11]:
some_digit = X_test[0]
print(y_test[0])
knn_clf.predict([some_digit])

6


array([[0, 0]], dtype=uint8)

In [13]:
some_digit = X_test[2]
print(y_test[2])
knn_clf.predict([some_digit])

1


array([[0, 1]], dtype=uint8)

In [18]:
y_train_knn_pred = cross_val_predict(knn_clf, X_train, y_multilabel, cv=3)
f1_score(y_multilabel, y_train_knn_pred, average="macro")

0.9500922726736858