In [2]:
import os
from matplotlib.image import imread
import urllib

In [10]:
# download image of ladybug
print(f"Current working directory: {os.getcwd()}")
images_path = os.path.join("..", "images", "unsupervised_learning")
os.makedirs(images_path, exist_ok=True)
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
filename = "ladybug.png"
print("Downloading", filename)
url = DOWNLOAD_ROOT + "images/unsupervised_learning/" + filename
urllib.request.urlretrieve(url, os.path.join(images_path, filename))

Current working directory: /root/statistical-learning/machine_learning_study/book-handson-geron/221123_01


('../images/unsupervised_learning/ladybug.png',
 <http.client.HTTPMessage at 0x7fa9082e24d0>)

In [3]:
image = imread(os.path.join("..", "images", "unsupervised_learning", "ladybug.png"))

In [4]:
image.shape

(533, 800, 3)

In [6]:
type(image)

numpy.ndarray

In [11]:
426400
print(533*800)

426400


In [7]:
X = image.reshape(-1,3)

In [8]:
X

array([[0.09803922, 0.11372549, 0.00784314],
       [0.09411765, 0.10980392, 0.00392157],
       [0.09411765, 0.11372549, 0.        ],
       ...,
       [0.03921569, 0.22745098, 0.        ],
       [0.01960784, 0.20392157, 0.        ],
       [0.00784314, 0.1882353 , 0.        ]], dtype=float32)

In [9]:
X.shape

(426400, 3)

In [12]:
from sklearn.cluster import KMeans

In [13]:
kmeans = KMeans(n_clusters=8).fit(X)

In [14]:
kmeans

KMeans()

In [15]:
kmeans.cluster_centers_

array([[0.09305994, 0.2452    , 0.01553079],
       [0.8857232 , 0.72715247, 0.03403426],
       [0.21052375, 0.37802467, 0.0539679 ],
       [0.6085664 , 0.6276636 , 0.3829402 ],
       [0.02133891, 0.10642648, 0.00561903],
       [0.9837676 , 0.9366001 , 0.02580037],
       [0.36485192, 0.5185691 , 0.1516756 ],
       [0.75873494, 0.21251506, 0.0447444 ]], dtype=float32)

In [16]:
kmeans.labels_

array([4, 4, 4, ..., 0, 0, 4], dtype=int32)

In [17]:
kmeans.labels_.shape

(426400,)

In [20]:
image = imread(os.path.join("..","images","unsupervised_learning","ladybug.png"))

In [21]:
segmented_img = kmeans.cluster_centers_[kmeans.labels_]

In [23]:
segmented_img

array([[0.02133891, 0.10642648, 0.00561903],
       [0.02133891, 0.10642648, 0.00561903],
       [0.02133891, 0.10642648, 0.00561903],
       ...,
       [0.09305994, 0.2452    , 0.01553079],
       [0.09305994, 0.2452    , 0.01553079],
       [0.02133891, 0.10642648, 0.00561903]], dtype=float32)

In [24]:
segmented_img.shape

(426400, 3)

In [25]:
segmented_img = segmented_img.reshape(image.shape)