In [31]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()

In [8]:
type(iris)

sklearn.utils._bunch.Bunch

In [9]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [14]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
type(iris.keys())

dict_keys

In [35]:
X = iris["data"][:,1:3]

In [36]:
X.shape

(150, 2)

In [13]:
type(X)

numpy.ndarray

In [37]:
from sklearn.cluster import KMeans
k = 5
kmeans = KMeans(n_clusters=k)
y_pred = kmeans.fit_predict(X)

In [38]:
y_pred

array([0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 4, 0, 0, 0, 4, 4, 4, 0, 4, 4, 0, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       4, 0, 4, 0, 4, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3,
       1, 1, 3, 1, 1, 1, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 3, 3, 3,
       3, 1, 3, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1], dtype=int32)

In [40]:
y_pred is kmeans.labels_

True

In [41]:
kmeans.labels_

array([0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 4, 0, 0, 0, 4, 4, 4, 0, 4, 4, 0, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       4, 0, 4, 0, 4, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3,
       1, 1, 3, 1, 1, 1, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 3, 3, 3,
       3, 1, 3, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1], dtype=int32)

In [42]:
kmeans.cluster_centers_

array([[3.24      , 1.44285714],
       [2.90238095, 4.83571429],
       [2.6       , 3.94285714],
       [3.08333333, 5.90333333],
       [3.86666667, 1.50666667]])

In [43]:
X_new = np.array([[0,2],[3,2],[-3,3]])
kmeans.predict(X_new)

array([2, 0, 2], dtype=int32)

In [44]:
# mesure distance of the point to each centroid
# there are 5 clusters, and we have 3 points
kmeans.transform(X_new)

array([[3.28755352, 4.05771989, 3.24571932, 4.97422914, 3.89801089],
       [0.60663676, 2.83739405, 1.98360628, 3.90422279, 0.99724064],
       [6.43135241, 6.18125779, 5.6788185 , 6.74064455, 7.02717266]])

In [50]:
# set by hand the initial position of the centroids
good_init = np.array([[-3,3],[-3,2],[-3,1],[-1,2],[0,2]])
kmeans = KMeans(n_clusters=5, init=good_init, n_init=1)
kmeans.fit(X)

KMeans(init=array([[-3,  3],
       [-3,  2],
       [-3,  1],
       [-1,  2],
       [ 0,  2]]),
       n_clusters=5, n_init=1)

In [51]:
kmeans.inertia_

23.647056694271917

In [52]:
from sklearn.cluster import MiniBatchKMeans

In [53]:
minibatch_kmeans = MiniBatchKMeans(n_clusters=2)

In [55]:
minibatch_kmeans.fit(X)

MiniBatchKMeans(n_clusters=2)

In [56]:
from sklearn.metrics import silhouette_score

In [57]:
silhouette_score(X, kmeans.labels_)

0.5351050408878217