In [1]:
# https://www.udemy.com/course/learning-path-julia-explore-data-science-with-julia/learn/lecture/6792680?start=15#overview

In [2]:
# creating a vector, which is a column vector
[1, 2, 3]
# this is considered to be a 1 dimensional vector

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
# we have the concept of array, vector and matrix
Array{Int64, 1} == Vector{Int64}
# The array is more general than the vector
# the vector is a special case of the array
# the Vector is a 1-dimensional array

true

In [4]:
# we can create a horizontal array:
[1 2 3]
# Note that it is a 1x3 matrix with 2-dimensions

1×3 Array{Int64,2}:
 1  2  3

In [5]:
# the horizontal array is considered a matrix
Array{Int64, 2} == Matrix{Int64}
# Note that Matrix is a keyword, Array and Vector are keyword
# or at least they are Classes or types 

true

In [6]:
# We can build a matrix with 2 rows

matrix1 = [1 2 3 ; 4 5 6] 
# Note that it is a 2x3 matrix
# it indicates that it is an array of
# type Int64 with 2 dimensions

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [8]:
# this will find the size of the first dimension
# which is the line, that is there two lines
# in the matrix
size(matrix1, 1)

2

In [9]:
# the size of the second dimension
# of the matrix is 3
# that is the matrix has 3 columns
size(matrix1, 2)

3

In [10]:
# we can also find the number of dimensions
# inside the matrix
ndims(matrix1)
# we could have matrices with more dimensions
# those are called tensors

2

In [11]:
# we can also find the type of element
# inside the matrix
eltype(matrix1)

Int64

In [13]:
# we can create matrix with random values 
rand(3, 3)
# the random values are standard uniform values

3×3 Array{Float64,2}:
 0.14975   0.498644  0.466206
 0.492236  0.837081  0.241549
 0.445237  0.31077   0.958698

In [14]:
# We can define the range of integer values
# and the size of the matrix
rand(10:20, 5, 5)

5×5 Array{Int64,2}:
 12  18  13  18  19
 19  10  20  16  16
 16  17  20  18  17
 16  18  15  10  10
 18  13  11  12  16

In [26]:
matrix2 = rand(0:100, 4, 5)

4×5 Array{Int64,2}:
 59  83   5  66  62
 46   4  40  28   3
 87  70  22  39  86
 47  92  80  91  21

In [28]:
size(matrix2)

(4, 5)

In [27]:
size(matrix2, 1)

4

In [29]:
println(matrix2)

[59 83 5 66 62; 46 4 40 28 3; 87 70 22 39 86; 47 92 80 91 21]


In [30]:
typeof(matrix2)

Array{Int64,2}

In [32]:
size(matrix2, 1)

4

In [33]:
size(matrix2, 2)

5

In [34]:
# create identity matrix 
eye(3)

UndefVarError: UndefVarError: eye not defined

In [35]:
# Create a matrix using a list comprehension
matrix3 = [n + m for n in 1:4, m in 1:4]

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

In [36]:
matrix4 = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [38]:
matrix4[1, 1]

1

In [39]:
matrix4[2, 3]
# second line third column

6

In [40]:
matrix4[2, :]
# the whole second line
# but it is transformed into a vector, that is, a columnar array

3-element Array{Int64,1}:
 4
 5
 6

In [42]:
matrix4[:, 3]
# the whole third column

3-element Array{Int64,1}:
 3
 6
 9

In [43]:
matrix4

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [44]:
matrix4[1:2, 2:3]

2×2 Array{Int64,2}:
 2  3
 5  6

In [45]:
matrix4[2:end, 2:end]

2×2 Array{Int64,2}:
 5  6
 8  9

In [46]:
matrix_A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [47]:
matrix_B = [5 6; 7 8]

2×2 Array{Int64,2}:
 5  6
 7  8

In [50]:
# We can concatenate two matrices together
matrix_C = [matrix_B matrix_A] 

2×4 Array{Int64,2}:
 5  6  1  2
 7  8  3  4

In [51]:
matrix_D = [matrix_A; matrix_B] 

4×2 Array{Int64,2}:
 1  2
 3  4
 5  6
 7  8

In [52]:
hcat(matrix_A, matrix_B)

2×4 Array{Int64,2}:
 1  2  5  6
 3  4  7  8

In [53]:
vcat(matrix_A, matrix_B)

4×2 Array{Int64,2}:
 1  2
 3  4
 5  6
 7  8

In [54]:
matrix_A

2×2 Array{Int64,2}:
 1  2
 3  4

In [56]:
reshape(matrix_A, 1, 4)

1×4 Array{Int64,2}:
 1  3  2  4

In [57]:
reshape(matrix_A, 4, 1)

4×1 Array{Int64,2}:
 1
 3
 2
 4

In [58]:
matrix_A + matrix_B

2×2 Array{Int64,2}:
  6   8
 10  12

In [59]:
matrix_A 

2×2 Array{Int64,2}:
 1  2
 3  4

In [60]:
matrix_B

2×2 Array{Int64,2}:
 5  6
 7  8

In [61]:
# this is matrix product
matrix_A * matrix_B

2×2 Array{Int64,2}:
 19  22
 43  50

In [62]:
# we can element wise product
matrix_A .* matrix_B
# the . dot notation is used to indicate 
# that operation needs to be performed element
# by element

2×2 Array{Int64,2}:
  5  12
 21  32

In [64]:
matrix_A 

2×2 Array{Int64,2}:
 1  2
 3  4

In [63]:
matrix_A - 2
# it seems that we can't make matrix and scalar operations
# like this

MethodError: MethodError: no method matching -(::Array{Int64,2}, ::Int64)
Closest candidates are:
  -(::Complex{Bool}, ::Real) at complex.jl:307
  -(::Missing, ::Number) at missing.jl:115
  -(::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:108
  ...

In [65]:
matrix_A * 2
# but we can make matrix and scalar multiplication

2×2 Array{Int64,2}:
 2  4
 6  8

In [66]:
matrix_A .- 2
# we need to use the . dot notation
# to make peration with a matrix and scalar

2×2 Array{Int64,2}:
 -1  0
  1  2

In [67]:
matrix_A'
# to transpose a matrix

2×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  3
 2  4

In [68]:
inv(matrix_A)
# to invert a matrix
# note that it is transformed from 
# int to float 

2×2 Array{Float64,2}:
 -2.0   1.0
  1.5  -0.5

In [75]:
# can we build a struct with the same characteristics as this Array using C?
# lengths = Array(Float64, 1, 4) # create an empty (initialized with arbitrary values) array 
lengths = [0 0 0 0]

1×4 Array{Int64,2}:
 0  0  0  0

In [70]:
fname = "../data/iris.txt"

"../data/iris.txt"

In [83]:
open(fname) do file
    for line in eachline(file)
        # println(line)
        mlengths = line[1:16]
        # println(mlengths)
        arr_temp = split(mlengths)
        # println(arr_temp)
        arr_mlengths = [parse(Float64, str) for str in arr_temp]
        arr_mlengths = reshape(arr_mlengths, 1, 4)
        # println(typeof(arr_mlengths))
        global lengths = vcat(lengths, arr_mlengths)
    end
end

In [85]:
lengths 

151×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 5.1  3.5  1.4  0.2
 4.9  3.0  1.4  0.2
 4.7  3.2  1.3  0.2
 4.6  3.1  1.5  0.2
 5.0  3.6  1.4  0.2
 5.4  3.9  1.7  0.4
 4.6  3.4  1.4  0.3
 5.0  3.4  1.5  0.2
 4.4  2.9  1.4  0.2
 4.9  3.1  1.5  0.1
 5.4  3.7  1.5  0.2
 4.8  3.4  1.6  0.2
 ⋮              
 6.0  3.0  4.8  1.8
 6.9  3.1  5.4  2.1
 6.7  3.1  5.6  2.4
 6.9  3.1  5.1  2.3
 5.8  2.7  5.1  1.9
 6.8  3.2  5.9  2.3
 6.7  3.3  5.7  2.5
 6.7  3.0  5.2  2.3
 6.3  2.5  5.0  1.9
 6.5  3.0  5.2  2.0
 6.2  3.4  5.4  2.3
 5.9  3.0  5.1  1.8

In [86]:
# cut out the first line which have only values with zeros
lengths = lengths[2:end, :] 

150×4 Array{Float64,2}:
 5.1  3.5  1.4  0.2
 4.9  3.0  1.4  0.2
 4.7  3.2  1.3  0.2
 4.6  3.1  1.5  0.2
 5.0  3.6  1.4  0.2
 5.4  3.9  1.7  0.4
 4.6  3.4  1.4  0.3
 5.0  3.4  1.5  0.2
 4.4  2.9  1.4  0.2
 4.9  3.1  1.5  0.1
 5.4  3.7  1.5  0.2
 4.8  3.4  1.6  0.2
 4.8  3.0  1.4  0.1
 ⋮              
 6.0  3.0  4.8  1.8
 6.9  3.1  5.4  2.1
 6.7  3.1  5.6  2.4
 6.9  3.1  5.1  2.3
 5.8  2.7  5.1  1.9
 6.8  3.2  5.9  2.3
 6.7  3.3  5.7  2.5
 6.7  3.0  5.2  2.3
 6.3  2.5  5.0  1.9
 6.5  3.0  5.2  2.0
 6.2  3.4  5.4  2.3
 5.9  3.0  5.1  1.8